# Override values for flatnotes
controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: dullage/flatnotes
          # -- image tag
          # @default -- chart.appVersion
          tag: v4.0.2
          # -- image pull policy
          pullPolicy: IfNotPresent

        # Command override to avoid chmods
        # command found here: https://github.com/Dullage/flatnotes/blob/master/entrypoint.sh#L32
        command: ["python"]
        args:
          - -m
          - uvicorn
          - main:app
          - --app-dir
          - server
          - --host
          - "0.0.0.0"
          - --port
          - "8080"

        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 15m
            memory: 100Mi

defaultPodOptions:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  nodeSelector:
    performance: medium

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-homelab"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: notes.pleasenoddos.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: flatnotes-tls
        hosts:
          - notes.pleasenoddos.com

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Clas
    storageClass: flatnotes-data
    size: 500Mi
    # Do not delete the pvc upon helm uninstall
    retain: true
