# Override values for flatnotes

image:
  # -- image repository
  repository: dullage/flatnotes
  # -- image tag
  # @default -- chart.appVersion
  tag: v3.0.0
  # -- image pull policy
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: notes.pleasenoddos.com
        paths:
          - path: /

persistence:
  data:
    enabled: true
    mountPath: /data
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Clas
    storageClass: flatnotes-data
    size: 500Mi
    # Do not delete the pvc upon helm uninstall
    retain: true

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 15m
    memory: 100Mi

nodeSelector:
  kubernetes.io/arch: amd64
  performance: medium
