apiVersion: v1
kind: PersistentVolume
metadata:
  name: flatnotes-data
spec:
  storageClassName: flatnotes-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/ZFS-3.6TB/tank/flatnotes-data
    server: truenas-1.tgp
