# Override values for Focalboard.

nameOverride: focal

image:
  tag: 0.8.0
  pullPolicy: Always

controller:
  strategy: RollingUpdate

# -- environment variables. See more environment variables in the [image entrypoint script](https://github.com/FlipEnergy/container-images/blob/main/focalboard/entrypoint.sh)
# @default -- See below
env:
  SERVER_ROOT: https://focal.pleasenoddos.com
  DBTYPE: postgres
  FOCALBOARD_DB_MAX_IDLE_CONNS: 4
  FOCALBOARD_DB_MAX_OPEN_CONNS: 60


ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: focal.pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

nodeSelector: {}
