# Override values for Cryptofolio

env:
  TZ: UTC

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: crypto.tgp
        paths:
          - path: /

resources:
  limits:
    memory: 75Mi
  requests:
    cpu: 100m
    memory: 50Mi

persistence:
  data:
    enabled: true
    mountPath: /var/www/html/api/data
    accessMode: ReadWriteOnce
    storageClass: cryptofolio-data
    size: 100Mi
    # Do not delete the pvc upon helm uninstall
    retain: true

nodeSelector:
  performance: low
