# Override values for Cryptofolio

image:
  # -- image tag
  tag: V.2.2.0

env:
  TZ: UTC

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: crypto.tgp
        paths:
          - path: /

resources:
  limits:
    cpu: 500m
    memory: 75Mi
  requests:
    cpu: 500m
    memory: 50Mi

persistence:
  data:
    enabled: true
    mountPath: /var/www/html/api/data
    accessMode: ReadWriteOnce
    storageClass: cryptofolio-data
    size: 100Mi

nodeSelector:
  kubernetes.io/arch: arm64
  performance: low
  type: app
