# wg-access-server config

# Note: on your phone, to allow chromecast to work and allow access to your local network,
#   in the peer section, add your subnet to the front and check Exclude private IPs.

config:
  externalHost: 140.238.137.31
  vpn:
    cidr: "10.45.0.0/24"
  dns:
    enabled: true

wireguard:
  service:
    type: LoadBalancer

persistence:
  enabled: true
  # Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  #
  storageClass: local-path
  size: 100Mi

strategy:
  type: RollingUpdate

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 50m
    memory: 125Mi
