apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  storageClassName: postgresql-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-SSD-460GB/SSD-tank/postgresql-data
    server: truenas-1.tgp
