apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  storageClassName: postgresql-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/ZFS-3.6TB/tank/postgresql-data
    server: truenas-1.tgp
