apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: postgresql
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/postgresql-data
    server: truenas-1.tgp
