apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncast-config
spec:
  storageClassName: owncast-config
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/owncast-config
    server: truenas-1.tgp
