apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncast
spec:
  storageClassName: owncast
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/owncast-config
    server: truenas-1
