apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncast
spec:
  storageClassName: owncast
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/owncast-data
    server: truenas-1.tgp
