apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  storageClassName: prometheus
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/prometheus-data
    server: truenas-1.tgp
