# Override values for kube-ops-view in oracle

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: kube.pleasenoddos.com
        paths:
          - path: /

nodeSelector:
  kubernetes.io/arch: amd64
  performance: medium
