# wg-access-server config

config:
  externalHost: wg.pleasenoddos.com
  vpn:
    cidr: "10.44.0.0/24"
  dns:
    enabled: true
    upstream:
      - 10.69.0.1

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-homelab"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - wireguard.computersbarely.work
  tls:
    - secretName: wireguard-tls
      hosts:
        - wireguard.computersbarely.work

nodeSelector:
  performance: medium

persistence:
  enabled: true
  storageClass: wireguard-data
