# Default values for soft-serve.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: charmcli/soft-serve
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 23231

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector:
  performance: low

tolerations: []

affinity: {}

persistence:
  data:
    storage: 1Gi
    nfsPath: /mnt/ZFS-3.6TB/tank/soft-serve-data
    nfsServer: truenas-1.tgp
