image:
  # -- image repository
  repository: linuxserver/duplicati
  # -- image tag
  tag: version-v2.0.6.3-2.0.6.3_beta_2021-06-17

# See more environment variables in the [duplicati documentation](https://github.com/linuxserver/docker-duplicati#parameters)
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Specify the user ID the application will run as
  PUID: "1000"
  # -- Specify the group ID the application will run as
  PGID: "1000"

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
      - host: duplicati.tgp
        paths:
          - path: /
            pathType: Prefix
            service:
              port: 8200

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    # Persistent Volume Storage Class
    storageClass: duplicati-config
    accessMode: ReadWriteOnce
    size: 100Mi
  source:
    enabled: true
    # Persistent Volume Storage Class
    storageClass: duplicati-source
    accessMode: ReadWriteOnce
    size: 3500Gi
