apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
spec:
  storageClassName: vaultwarden-data
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-SSD-460GB/SSD-tank/vaultwarden-data
    server: truenas-1.tgp
