apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data
spec:
  storageClassName: vaultwarden-data
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/ZFS-3.6TB/tank/vaultwarden-data
    server: truenas-1.tgp
