# InfluxDB2 override values

nodeSelector:
  kubernetes.io/hostname: oraclek8sarmnode2

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

## Extra environment variables to configure influxdb
## e.g.
# env:
#   - name: FOO
#     value: BAR
#   - name: BAZ
#     valueFrom:
#       secretKeyRef:
#         name: my-secret
#         key: my-key
env: {}

## Persist data to a persistent volume
##
persistence:
  enabled: true
  # If true will use an existing PVC instead of creating one
  useExisting: false
  # Name of existing PVC to be used in the influx deployment
  name: influxdb2
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 10Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 1500m
    memory: 6Gi
  requests:
    cpu: 500m
    memory: 3Gi

ingress:
  enabled: false
  tls: false
  # secretName: my-tls-cert # only needed if tls above is true
  hostname: influx.pleasenoddos.com
  annotations: {}
    # kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/tls-acme: "true"
  path: /
