# InfluxDB2 override values

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

env:
  - name: INFLUXD_SESSION_LENGTH
    value: "525600" # 1 year

## Allow executing custom init scripts
## If the container finds any files with the .sh extension inside of the
## /docker-entrypoint-initdb.d folder, it will execute them.
## When multiple scripts are present, they will be executed in lexical sort order by name.
## For more details see Custom Initialization Scripts in https://hub.docker.com/_/influxdb
initScripts:
  enabled: true
  scripts:
    init.sh: |+
      #!/bin/bash
      influx apply --force yes -u https://gist.githubusercontent.com/FlipEnergy/1ee2959e83043913611ce66872f2e213/raw/262909834100e258772e4bbef906af9ce281fac5/system_dashboard.json

## Persist data to a persistent volume
##
persistence:
  enabled: true
  # If true will use an existing PVC instead of creating one
  useExisting: false
  # Name of existing PVC to be used in the influx deployment
  name: influxdb2
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 30Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    memory: 6Gi
  requests:
    cpu: 2
    memory: 3Gi

ingress:
  enabled: true
  tls: true
  secretName: influxdb2-tls
  hostname: influx.pleasenoddos.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-homelab"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  path: /
