# InfluxDB2 override values

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

## Persist data to a persistent volume
##
persistence:
  enabled: true
  # If true will use an existing PVC instead of creating one
  useExisting: false
  # Name of existing PVC to be used in the influx deployment
  name: influxdb2
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 30Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 1500m
    memory: 6Gi
  requests:
    cpu: 500m
    memory: 3Gi

ingress:
  enabled: true
  tls: true
  # secretName: my-tls-cert # only needed if tls above is true
  hostname: influx.pleasenoddos.com
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  path: /
