#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- See the following files for additional environment variables:
# https://github.com/paperless-ngx/paperless-ngx/tree/main/docker/compose/
# https://github.com/paperless-ngx/paperless-ngx/blob/main/paperless.conf.example
# @default -- See below
env:
  PAPERLESS_REDIS: redis://redis-master.redis/1
  PAPERLESS_CONSUMER_RECURSIVE: true
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: true

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: paperless.tgp
        paths:
          - path: /

resources:
  limits:
    cpu: 1
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 250Mi

nodeSelector:
  kubernetes.io/arch: amd64
  performance: medium

persistence:
  # -- Configure persistence for data.
  # @default -- See values.yaml
  data:
    enabled: true
    storageClass: paperless-data
    size: 100Mi
  # -- Configure persistence for media.
  # @default -- See values.yaml
  media:
    enabled: true
    storageClass: paperless-media
    size: 3Gi
  # -- Configure volume to monitor for new documents.
  # @default -- See values.yaml
  consume:
    enabled: true
    storageClass: paperless-consume
    size: 3Gi
