apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless
spec:
  storageClassName: paperless
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/paperless-data
    server: truenas-1.tgp
