apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-config
spec:
  storageClassName: navidrome-config
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/navidrome-config
    server: truenas-1.tgp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-music
spec:
  storageClassName: navidrome-music
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/ZFS-3.6TB/tank/cold-storage/Music
    server: truenas-1.tgp
