# Default values for restic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ad-hoc pod for interacting
replicaCount: 1

image:
  repository: flipenergy/restic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

schedule: "0 8 * * *"

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

backoffLimit: 1

restartPolicy: Never

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

env:
  RESTIC_PROGRESS_FPS: 1

secret:
  RESTIC_PASSWORD: placeholder

resources: {}

persistence:
  source: {}

nodeSelector: {}

jobNodeSelector: {}

tolerations: []

affinity: {}
