# Override values for Nextcloud

## Official nextcloud image version
## ref: https://hub.docker.com/r/library/nextcloud/tags/
##
# image:
#   repository: nextcloud
#   tag: 25.0.4-apache

## Allowing use of ingress controllers
## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-homelab"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: 1G
  tls:
    - secretName: nextcloud-tls
      hosts:
        - cloud.pleasenoddos.com

phpClientHttpsFix:
  enabled: true
  protocol: https

nextcloud:
  host: cloud.pleasenoddos.com

  mail:
    enabled: true
    fromAddress: dennis.zhang.nrg
    domain: gmail.com
    smtp:
      host: smtp.gmail.com
      secure: tls
      port: 587
      authtype: LOGIN

  # Extra mounts for the pods. Example shown is for connecting a legacy NFS volume
  # to NextCloud pods in Kubernetes. This can then be configured in External Storage
  extraVolumes:
    - name: extra-mounts
      configMap:
        name: nextcloud-extra-mounts
        defaultMode: 0777
  extraVolumeMounts:
    - name: extra-mounts
      mountPath: /entrypoint.sh
      subPath: entrypoint.sh
      readOnly: true
    - name: extra-mounts
      mountPath: /var/www/html/config/previews.config.php
      subPath: previews.config.php
      readOnly: true

  ##
  ## Extra environment variables
  extraEnv:
    - name: REDIS_HOST
      value: redis-master.redis
    - name: PHP_MEMORY_LIMIT
      value: 4G
    - name: PHP_UPLOAD_LIMIT
      value: 20G

internalDatabase:
  enabled: false

##
## External database configuration
##
externalDatabase:
  enabled: true
  ## Supported database engines: mysql or postgresql
  type: postgresql
  ## Database host
  host: postgresql.postgresql
  ## Database name
  database: nextcloud

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  # Nextcloud Data (/var/www/html)
  enabled: true
  annotations: {}
  # nextcloud data Persistent Volume Storage Class
  # If defined, storageClassName: <storageClass>
  # If set to "-", storageClassName: "", which disables dynamic provisioning
  # If undefined (the default) or set to null, no storageClassName spec is
  #   set, choosing the default provisioner.  (gp2 on AWS, standard on
  #   GKE, AWS & OpenStack)
  #
  storageClass: nextcloud-data

  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  accessMode: ReadWriteOnce
  size: 3Ti

resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 2
    memory: 2Gi

nodeSelector:
  performance: high

tolerations: []

affinity: {}

## Liveness and readiness probe values
## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
##
livenessProbe:
  enabled: false
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 60
  successThreshold: 1
