apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  storageClassName: nextcloud-data
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/nextcloud-data
    server: truenas-1.tgp
