# Override values for libreddit.

image:
  # -- image repository
  repository: libreddit/libreddit
  # -- image tag
  # @default -- chart.appVersion
  tag: armv7
  # -- image pull policy
  pullPolicy: Always

controller:
  strategy: RollingUpdate

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: reddit.pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    memory: 300Mi
  requests:
    cpu: 500m
    memory: 150Mi
