# Override values for cloudflareddns

# https://hotio.dev/containers/cloudflareddns/

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: ghcr.io/hotio/cloudflareddns
          # -- image tag
          # @default -- chart.appVersion
          tag: release
          # -- image pull policy
          pullPolicy: Always
        env:
          PUID: 1000
          PGID: 1000
          LOG_LEVEL: 2

        resources: {}
          # limits:
          #   memory: 100Mi
          # requests:
          #   memory: 50Mi


defaultPodOptions:
  nodeSelector:
    performance: medium

service:
  main:
    enabled: false
    controller: main
