# Override Values for cert-manager
nodeSelector:
  performance: medium

webhook:
  nodeSelector:
    performance: medium

cainjector:
  nodeSelector:
    performance: medium

startupapicheck:
  nodeSelector:
    performance: medium
