# Override Values for cert-manager
nodeSelector:
  kubernetes.io/arch: amd64

webhook:
  nodeSelector:
    kubernetes.io/arch: amd64

cainjector:
  nodeSelector:
    kubernetes.io/arch: amd64

startupapicheck:
  nodeSelector:
    kubernetes.io/arch: amd64
