# dokuwiki override values

image:
  # -- image tag
  tag: version-2020-07-29

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: doku.pleasenoddos.com
        paths:
          - path: /

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: /config
    storageClass: dokuwiki-data
    accessMode: ReadWriteOnce
    size: 1Gi
    # Do not delete the pvc upon helm uninstall
    retain: true
