apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "restic.fullname" . }}
  labels:
    {{- include "restic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "restic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "restic.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: source
          persistentVolumeClaim:
            claimName: {{ include "restic.fullname" . }}-source
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 16 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            - -c
            - sleep infinity
          volumeMounts:
            - mountPath: /source
              name: source
          resources:
            {{- toYaml .Values.resources | nindent 16 }}
          {{- with .Values.env }}
          env:
            {{- range $name, $value := . }}
            - name: {{ quote $name }}
              value: {{ quote $value }}
            {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
