apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "restic.fullname" . }}-source
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.source.storage }}
  storageClassName: {{ include "restic.fullname" . }}-source
  volumeMode: Filesystem
  volumeName: {{ include "restic.fullname" . }}-source
