# Override values for stirling-pdf
controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: vicwomg/pikaraoke
          # -- image tag
          # @default -- chart.appVersion
          tag: 1.13.0
          # -- image pull policy
          pullPolicy: IfNotPresent

        # Command override to set params
        # command found here: https://github.com/vicwomg/pikaraoke/blob/master/Dockerfile
        command: ["poetry"]
        args:
          - run
          - pikaraoke
          - -d
          - /data/
          - --headless
          - -l10
          - --url
          - https://karaoke.pleasenoddos.com
          - --normalize-audio
          - --complete-transcode-before-play

        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 200Mi

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

defaultPodOptions:
  nodeSelector:
    performance: high

service:
  main:
    controller: main
    ports:
      http:
        port: 5555

ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-homelab"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
    hosts:
      - host: karaoke.pleasenoddos.com
        paths:
          - path: /
            service:
              identifier: main
              port: http
    tls:
      - secretName: pikaraoke-tls
        hosts:
          - karaoke.pleasenoddos.com

persistence:
  data:
    enabled: true
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Clas
    storageClass: pikaraoke-data
    size: 10Gi
    # Do not delete the pvc upon helm uninstall
    retain: true
