# Override values for goldilocks

vpa:
  # vpa.enabled -- If true, the vpa will be installed as a sub-chart
  enabled: true
  updater:
    enabled: false

dashboard:
  replicaCount: 1
  ingress:
    # dashboard.ingress.enabled -- Enables an ingress object for the dashboard.
    enabled: true

    # dashboard.ingress.ingressClassName -- From Kubernetes 1.18+ this field is supported in case your ingress controller supports it. When set, you do not need to add the ingress class as annotation.
    ingressClassName:
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: goldilocks.tgp
        paths:
          - path: /
            type: ImplementationSpecific
  nodeSelector: {}
