apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb2
spec:
  storageClassName: influxdb2
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/data/influxdb2
    server: k8s-nfs-1.tgp
