apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-news-updater.fullname" . }}
  labels: {{- include "nextcloud-news-updater.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with .Values.secret }}
  {{- toYaml . | nindent 2 }}
{{- end }}
