apiVersion: v1
kind: PersistentVolume
metadata:
  name: ihatemoney-data
spec:
  storageClassName: ihatemoney-data
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/ihatemoney-data
    server: truenas-1.tgp
