# Default values for restic.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: restic/restic
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

# schedule: "6 45 * * *"
schedule: "*/10 * * * *"

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 3

backoffLimit: 3
activeDeadlineSeconds: 600

restartPolicy: OnFailure

podAnnotations: {}

podSecurityContext: {}

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

env:
  RESTIC_PROGRESS_FPS: 1

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

persistence:
  source:
    storage: 3500Gi
    nfsPath: /mnt/ZFS-3.6TB/storage
    nfsServer: truenas-1.tgp

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
              - postgresql
        topologyKey: kubernetes.io/hostname
