image:
  # -- image tag
  tag: 10.7.6

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    hosts:
      - host: jelly.pleasenoddos.com
        paths:
          - path: /

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Class
    storageClass: jellyfin-config
    size: 1Gi
    # Do not delete the pvc upon helm uninstall
    retain: false
  music:
    enabled: true
    mountPath: /music
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Class
    storageClass: jellyfin-music
    size: 100Gi
    # Do not delete the pvc upon helm uninstall
    retain: false
  videos:
    enabled: true
    mountPath: /videos
    accessMode: ReadWriteOnce
    # Persistent Volume Storage Class
    storageClass: jellyfin-videos
    size: 300Gi
    # Do not delete the pvc upon helm uninstall
    retain: false

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 1536Mi

nodeSelector:
  kubernetes.io/arch: amd64
  performance: medium
  type: app
