apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  storageClassName: jellyfin-config
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/jellyfin-config
    server: truenas-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music
spec:
  storageClassName: jellyfin-music
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/syncthing-data/music
    server: truenas-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-videos
spec:
  storageClassName: jellyfin-videos
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 300Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/cold-storage/Videos
    server: truenas-1
