# Override values for Hastebin.

nameOverride: haste

image:
  repository: ghcr.io/k8s-at-home/haste-server
  pullPolicy: Always
  tag: latest

controller:
  strategy: RollingUpdate

# See more environment variables in the haste-server documentation
# https://github.com/rwaltr/haste-server
env:
  STORAGE_FILEPATH: "/data"
  STORAGE_TYPE: "file"

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: haste.pleasenoddos.com
        paths:
          - path: /

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

persistence:
  data:
    enabled: true
    # Persistent Volume Storage Class
    storageClass: local-path
    accessMode: ReadWriteOnce
    size: 5Gi
    # Do not delete the pvc upon helm uninstall
    retain: true
