apiVersion: v1
kind: PersistentVolume
metadata:
  name: ytdl-config
spec:
  storageClassName: ytdl-config
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/storage/ytdl-data/config
    server: truenas-1.tgp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ytdl-subs
spec:
  storageClassName:  ytdl-subs
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/storage/ytdl-data/subscriptions
    server: truenas-1.tgp
