apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
spec:
  storageClassName: freshrss-data
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/freshrss-data
    server: truenas-1
