apiVersion: v1
kind: PersistentVolume
metadata:
  name: habittrove-data
spec:
  storageClassName: habittrove-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/habittrove-data
    server: truenas-1.tgp
