apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing
spec:
  storageClassName: syncthing
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/syncthing-data
    server: truenas-1
