# Override values for syncthing.

image:
  tag: 1.18.3
  pullPolicy: IfNotPresent

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
    - host: syncthing.tgp
      paths:
        - path: /

resources:
  limits:
    cpu: 500m
    memory: 1500Mi
  requests:
    cpu: 50m
    memory: 750Mi

persistence:
  data:
    enabled: true
    mountPath: /var/syncthing
    storageClass: syncthing
    accessMode: ReadWriteOnce
    size: 1Ti
