# Override values for syncthing.

image:
  tag: 1.18.1
  pullPolicy: IfNotPresent

podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000

ingress:
  main:
    enabled: true
    hosts:
    - host: syncthing.tgp
      paths:
        - path: /

resources:
  limits:
    cpu: '1'
    memory: 1500Mi
  requests:
    cpu: 500m
    memory: 750Mi

persistence:
  data:
    enabled: true
    emptyDir:
      enabled: false
    mountPath: /var/syncthing
    storageClass: syncthing
    accessMode: ReadWriteOnce
    size: 500Gi
