# Override values for syncthing.

image:
  tag: 1.20.1
  pullPolicy: IfNotPresent

securityContext:
  runAsUser: 1000
  runAsNonRoot: true

ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: syncthing.tgp
        paths:
          - path: /

resources:
  limits:
    memory: 1500Mi
  requests:
    cpu: 500m
    memory: 750Mi

persistence:
  data:
    enabled: true
    mountPath: /var/syncthing
    storageClass: syncthing
    accessMode: ReadWriteOnce
    size: 1Ti
    # Do not delete the pvc upon helm uninstall
    retain: true

nodeSelector:
  performance: low
