apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-data
spec:
  storageClassName: wireguard-data
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/ZFS-3.6TB/tank/wireguard-data
    server: truenas-1.tgp
