apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-data
spec:
  storageClassName: gonic-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/gonic-data
    server: truenas-1.tgp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gonic-music
spec:
  storageClassName: gonic-music
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    path: /mnt/ZFS-3.6TB/tank/cold-storage/Music
    server: truenas-1.tgp
