apiVersion: v1
kind: PersistentVolume
metadata:
  name: stash-data
spec:
  storageClassName: stash-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/ZFS-3.6TB/tank/stash-data
    server: truenas-1.tgp
