# Override Values for cert-manager

installCRDs: true

cluster-resource-namespace: cert-manager

# Comma separated string with host and port of the recursive nameservers cert-manager should query
dns01RecursiveNameservers: 1.1.1.1:53

# Forces cert-manager to only use the recursive nameservers for verification.
# Enabling this option could cause the DNS01 self check to take longer due to caching performed by the recursive nameservers
dns01RecursiveNameserversOnly: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi

prometheus:
  enabled: false
